name: Convert WebM to GIF

on:
  push:
    paths:
      - 'res/video/webm/*.webm'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Check if there are WebM files
        id: check_files
        run: |
          if [ -z "$(ls -A res/video/webm/*.webm 2>/dev/null | grep -v test_0000.webm)" ]; then
            echo "No WebM files found."
            echo "files_found=false" >> $GITHUB_ENV
          else
            echo "WebM files found."
            echo "files_found=true" >> $GITHUB_ENV
          fi

      - name: Set up FFmpeg
        if: steps.check_files.outputs.files_found == 'true'
        run: chmod +x tools/ffmpeg

      - name: Convert WebM to GIF
        if: steps.check_files.outputs.files_found == 'true'
        run: |
          file=$(ls -t res/video/webm/*.webm | head -n 1)
          filename=$(basename "$file" .webm)
          tools/ffmpeg -i "$file" -loop 0 -vf "fps=10,scale=320:-1:flags=lanczos" -c:v gif -y "res/picture/gif/$filename.gif"

      - name: List GIF files
        if: steps.check_files.outputs.files_found == 'true'
        run: ls -l res/picture/gif

      - name: Commit and push GIFs
        if: steps.check_files.outputs.files_found == 'true'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
        run: |
          latest_gif=$(ls -t res/picture/gif/*.gif | head -n 1)
          if [ -z "$latest_gif" ] || [ "$latest_gif" = "res/picture/gif/test_0000.gif" ]; then
            echo "No GIF files found."
            exit 1
          fi
          curl -F "chat_id=$OWNER_ID" -F "document=@$latest_gif" https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument
