name: Convert WebM to GIF

on:
  push:
    paths:
      - 'res/video/webm/*.webm' 

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4 

    - name: Check if there are WebM files
      id: check_files
      run: |
        if [ -z "$(ls -A res/video/webm/*.webm 2>/dev/null)" ]; then
          echo "No WebM files found."
          echo "::set-output name=files_found::false"
        else
          echo "WebM files found."
          echo "::set-output name=files_found::true"
        fi

    - name: Set up FFmpeg
      if: steps.check_files.outputs.files_found == 'true'
      run: sudo apt-get install -y ffmpeg

    - name: Convert WebM to GIF
      if: steps.check_files.outputs.files_found == 'true'
      run: |
        for file in res/video/webm/*.webm; do
          filename=$(basename "$file" .webm)
          ffmpeg -i "$file" "res/picture/gif/$filename.gif"
        done

    - name: List GIF files
      if: steps.check_files.outputs.files_found == 'true'
      run: ls -l res/picture/gif

    - name: Commit and push GIFs
      if: steps.check_files.outputs.files_found == 'true'
      run: |
        git config --global user.name "whysiki"
        git config --global user.email "whysiki@proton.me"
        git add res/picture/gif/*.gif
        git commit -m "Converted WebM to GIF"
        git push